spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.166.79:3306/exam_online
    username: root
    password: IiyoKoiyo_114514
server:
  port:
    23333