package cn.edu.xmu.examonline.model.po;

public class MajorPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.single_selection_num
     *
     * @mbggenerated
     */
    private Integer singleSelectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.multiple_selection_num
     *
     * @mbggenerated
     */
    private Integer multipleSelectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.judgement_num
     *
     * @mbggenerated
     */
    private Integer judgementNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.short_answer_num
     *
     * @mbggenerated
     */
    private Integer shortAnswerNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.name
     *
     * @return the value of major.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.name
     *
     * @param name the value for major.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.single_selection_num
     *
     * @return the value of major.single_selection_num
     *
     * @mbggenerated
     */
    public Integer getSingleSelectionNum() {
        return singleSelectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.single_selection_num
     *
     * @param singleSelectionNum the value for major.single_selection_num
     *
     * @mbggenerated
     */
    public void setSingleSelectionNum(Integer singleSelectionNum) {
        this.singleSelectionNum = singleSelectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.multiple_selection_num
     *
     * @return the value of major.multiple_selection_num
     *
     * @mbggenerated
     */
    public Integer getMultipleSelectionNum() {
        return multipleSelectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.multiple_selection_num
     *
     * @param multipleSelectionNum the value for major.multiple_selection_num
     *
     * @mbggenerated
     */
    public void setMultipleSelectionNum(Integer multipleSelectionNum) {
        this.multipleSelectionNum = multipleSelectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.judgement_num
     *
     * @return the value of major.judgement_num
     *
     * @mbggenerated
     */
    public Integer getJudgementNum() {
        return judgementNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.judgement_num
     *
     * @param judgementNum the value for major.judgement_num
     *
     * @mbggenerated
     */
    public void setJudgementNum(Integer judgementNum) {
        this.judgementNum = judgementNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.short_answer_num
     *
     * @return the value of major.short_answer_num
     *
     * @mbggenerated
     */
    public Integer getShortAnswerNum() {
        return shortAnswerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.short_answer_num
     *
     * @param shortAnswerNum the value for major.short_answer_num
     *
     * @mbggenerated
     */
    public void setShortAnswerNum(Integer shortAnswerNum) {
        this.shortAnswerNum = shortAnswerNum;
    }
}