package cn.edu.xmu.examonline.model.po;

public class PaperQuestPoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_quest.paper_id
     *
     * @mbggenerated
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_quest.quest_id
     *
     * @mbggenerated
     */
    private Integer questId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_quest.paper_id
     *
     * @return the value of paper_quest.paper_id
     *
     * @mbggenerated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_quest.paper_id
     *
     * @param paperId the value for paper_quest.paper_id
     *
     * @mbggenerated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_quest.quest_id
     *
     * @return the value of paper_quest.quest_id
     *
     * @mbggenerated
     */
    public Integer getQuestId() {
        return questId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_quest.quest_id
     *
     * @param questId the value for paper_quest.quest_id
     *
     * @mbggenerated
     */
    public void setQuestId(Integer questId) {
        this.questId = questId;
    }
}