package cn.edu.xmu.examonline.model.po;

public class PaperQuestPo extends PaperQuestPoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_quest.quest_index
     *
     * @mbggenerated
     */
    private Integer questIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_quest.quest_answer
     *
     * @mbggenerated
     */
    private String questAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_quest.quest_index
     *
     * @return the value of paper_quest.quest_index
     *
     * @mbggenerated
     */
    public Integer getQuestIndex() {
        return questIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_quest.quest_index
     *
     * @param questIndex the value for paper_quest.quest_index
     *
     * @mbggenerated
     */
    public void setQuestIndex(Integer questIndex) {
        this.questIndex = questIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_quest.quest_answer
     *
     * @return the value of paper_quest.quest_answer
     *
     * @mbggenerated
     */
    public String getQuestAnswer() {
        return questAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_quest.quest_answer
     *
     * @param questAnswer the value for paper_quest.quest_answer
     *
     * @mbggenerated
     */
    public void setQuestAnswer(String questAnswer) {
        this.questAnswer = questAnswer == null ? null : questAnswer.trim();
    }
}