package cn.edu.xmu.examonline.model.po;

import java.util.Date;

public class PaperPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.major1_id
     *
     * @mbggenerated
     */
    private Integer major1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.major2_id
     *
     * @mbggenerated
     */
    private Integer major2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.major3_id
     *
     * @mbggenerated
     */
    private Integer major3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.quest_num
     *
     * @mbggenerated
     */
    private Integer questNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.is_ended
     *
     * @mbggenerated
     */
    private Boolean isEnded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.id
     *
     * @return the value of paper.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.id
     *
     * @param id the value for paper.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.user_id
     *
     * @return the value of paper.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.user_id
     *
     * @param userId the value for paper.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.major1_id
     *
     * @return the value of paper.major1_id
     *
     * @mbggenerated
     */
    public Integer getMajor1Id() {
        return major1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.major1_id
     *
     * @param major1Id the value for paper.major1_id
     *
     * @mbggenerated
     */
    public void setMajor1Id(Integer major1Id) {
        this.major1Id = major1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.major2_id
     *
     * @return the value of paper.major2_id
     *
     * @mbggenerated
     */
    public Integer getMajor2Id() {
        return major2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.major2_id
     *
     * @param major2Id the value for paper.major2_id
     *
     * @mbggenerated
     */
    public void setMajor2Id(Integer major2Id) {
        this.major2Id = major2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.major3_id
     *
     * @return the value of paper.major3_id
     *
     * @mbggenerated
     */
    public Integer getMajor3Id() {
        return major3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.major3_id
     *
     * @param major3Id the value for paper.major3_id
     *
     * @mbggenerated
     */
    public void setMajor3Id(Integer major3Id) {
        this.major3Id = major3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.quest_num
     *
     * @return the value of paper.quest_num
     *
     * @mbggenerated
     */
    public Integer getQuestNum() {
        return questNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.quest_num
     *
     * @param questNum the value for paper.quest_num
     *
     * @mbggenerated
     */
    public void setQuestNum(Integer questNum) {
        this.questNum = questNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.start_time
     *
     * @return the value of paper.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.start_time
     *
     * @param startTime the value for paper.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.end_time
     *
     * @return the value of paper.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.end_time
     *
     * @param endTime the value for paper.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.is_ended
     *
     * @return the value of paper.is_ended
     *
     * @mbggenerated
     */
    public Boolean getIsEnded() {
        return isEnded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.is_ended
     *
     * @param isEnded the value for paper.is_ended
     *
     * @mbggenerated
     */
    public void setIsEnded(Boolean isEnded) {
        this.isEnded = isEnded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.name
     *
     * @return the value of paper.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.name
     *
     * @param name the value for paper.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}