package cn.edu.xmu.examonline.model.po;

public class QuestPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.major_id
     *
     * @mbggenerated
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_num
     *
     * @mbggenerated
     */
    private Integer selectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_a
     *
     * @mbggenerated
     */
    private String selectionA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_b
     *
     * @mbggenerated
     */
    private String selectionB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_c
     *
     * @mbggenerated
     */
    private String selectionC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_d
     *
     * @mbggenerated
     */
    private String selectionD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_e
     *
     * @mbggenerated
     */
    private String selectionE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.selection_f
     *
     * @mbggenerated
     */
    private String selectionF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.id
     *
     * @return the value of quest.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.id
     *
     * @param id the value for quest.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.major_id
     *
     * @return the value of quest.major_id
     *
     * @mbggenerated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.major_id
     *
     * @param majorId the value for quest.major_id
     *
     * @mbggenerated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.type_id
     *
     * @return the value of quest.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.type_id
     *
     * @param typeId the value for quest.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.description
     *
     * @return the value of quest.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.description
     *
     * @param description the value for quest.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.answer
     *
     * @return the value of quest.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.answer
     *
     * @param answer the value for quest.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_num
     *
     * @return the value of quest.selection_num
     *
     * @mbggenerated
     */
    public Integer getSelectionNum() {
        return selectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_num
     *
     * @param selectionNum the value for quest.selection_num
     *
     * @mbggenerated
     */
    public void setSelectionNum(Integer selectionNum) {
        this.selectionNum = selectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_a
     *
     * @return the value of quest.selection_a
     *
     * @mbggenerated
     */
    public String getSelectionA() {
        return selectionA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_a
     *
     * @param selectionA the value for quest.selection_a
     *
     * @mbggenerated
     */
    public void setSelectionA(String selectionA) {
        this.selectionA = selectionA == null ? null : selectionA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_b
     *
     * @return the value of quest.selection_b
     *
     * @mbggenerated
     */
    public String getSelectionB() {
        return selectionB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_b
     *
     * @param selectionB the value for quest.selection_b
     *
     * @mbggenerated
     */
    public void setSelectionB(String selectionB) {
        this.selectionB = selectionB == null ? null : selectionB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_c
     *
     * @return the value of quest.selection_c
     *
     * @mbggenerated
     */
    public String getSelectionC() {
        return selectionC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_c
     *
     * @param selectionC the value for quest.selection_c
     *
     * @mbggenerated
     */
    public void setSelectionC(String selectionC) {
        this.selectionC = selectionC == null ? null : selectionC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_d
     *
     * @return the value of quest.selection_d
     *
     * @mbggenerated
     */
    public String getSelectionD() {
        return selectionD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_d
     *
     * @param selectionD the value for quest.selection_d
     *
     * @mbggenerated
     */
    public void setSelectionD(String selectionD) {
        this.selectionD = selectionD == null ? null : selectionD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_e
     *
     * @return the value of quest.selection_e
     *
     * @mbggenerated
     */
    public String getSelectionE() {
        return selectionE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_e
     *
     * @param selectionE the value for quest.selection_e
     *
     * @mbggenerated
     */
    public void setSelectionE(String selectionE) {
        this.selectionE = selectionE == null ? null : selectionE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.selection_f
     *
     * @return the value of quest.selection_f
     *
     * @mbggenerated
     */
    public String getSelectionF() {
        return selectionF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.selection_f
     *
     * @param selectionF the value for quest.selection_f
     *
     * @mbggenerated
     */
    public void setSelectionF(String selectionF) {
        this.selectionF = selectionF == null ? null : selectionF.trim();
    }
}