package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.po.MajorPo;
import cn.edu.xmu.examonline.model.po.MajorPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */

    List<MajorPo> selectAll();

    List<MajorPo> selectByName(String name);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int insert(MajorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int insertSelective(MajorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    List<MajorPo> selectByExample(MajorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    MajorPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MajorPo record, @Param("example") MajorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MajorPo record, @Param("example") MajorPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MajorPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MajorPo record);
}