package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.po.PaperQuestPo;
import cn.edu.xmu.examonline.model.po.PaperQuestPoExample;
import cn.edu.xmu.examonline.model.po.PaperQuestPoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperQuestPoMapper {

    int deleteByPaperId(int id);

    int deleteByQuestId(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PaperQuestPoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int insert(PaperQuestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int insertSelective(PaperQuestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    List<PaperQuestPo> selectByExample(PaperQuestPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    PaperQuestPo selectByPrimaryKey(PaperQuestPoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaperQuestPo record, @Param("example") PaperQuestPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaperQuestPo record, @Param("example") PaperQuestPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaperQuestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_quest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaperQuestPo record);
}