package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.po.PaperPo;
import cn.edu.xmu.examonline.model.po.PaperPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperPoMapper {

    List<PaperPo> selectByUserId(int id);

    List<PaperPo> selectByUserIdAndName(PaperPo po);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int insert(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int insertSelective(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    List<PaperPo> selectByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    PaperPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaperPo record);
}