package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.po.UserProfilePo;
import cn.edu.xmu.examonline.model.po.UserTypePo;
import cn.edu.xmu.examonline.model.po.UserTypePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTypePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    String deleteByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int insert(UserTypePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int insertSelective(UserTypePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    List<UserTypePo> selectByExample(UserTypePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    UserTypePo selectByPrimaryKey(Integer id);

    List<UserTypePo> selectByName(String name);

    List<UserTypePo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserTypePo record, @Param("example") UserTypePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserTypePo record, @Param("example") UserTypePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTypePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTypePo record);
}