package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.po.UserPo;
import cn.edu.xmu.examonline.model.po.UserProfilePo;
import cn.edu.xmu.examonline.model.po.UserProfilePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProfilePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    String deleteByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insert(UserProfilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insertSelective(UserProfilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    List<UserProfilePo> selectByExample(UserProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    UserProfilePo selectByPrimaryKey(Integer userId);

    List<UserProfilePo> selectByName(String name);

    List<UserProfilePo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserProfilePo record, @Param("example") UserProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserProfilePo record, @Param("example") UserProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserProfilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserProfilePo record);
}