package cn.edu.xmu.examonline.mapper;

import cn.edu.xmu.examonline.model.bo.User;
import cn.edu.xmu.examonline.model.po.UserPo;
import cn.edu.xmu.examonline.model.po.UserPoExample;
import java.util.List;

import cn.edu.xmu.examonline.model.po.UserProfilePo;
import org.apache.ibatis.annotations.Param;

public interface UserPoMapper {

    int deleteByPrimaryKey(Integer userId);

    String deleteByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<UserPo> selectByExample(UserPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    UserPo selectByPrimaryKey(Integer userId);

    List<UserPo> selectByName(String name);

    List<UserPo> selectByType(Integer typeId);

    List<UserPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPo record, @Param("example") UserPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPo record, @Param("example") UserPoExample example);

    int updateByPrimaryKey(UserPo record);
}